language: python
python:
- 3.8
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: m1cO6/9Ec6jwe7rs0xOG/obeuWQLzYWU0g5hlJHIFTML3mJnu0u4dKeONDRE5cb7ZGz3pp6cwMzfRCXpVMQr0MwUQsQXQEBfwOnx1PLPIWkvWlzb3LiV4H77V2KbV4perxhZPiVwJEqVNw0KKZVVexeJYNlgnbjZGug2tLlQjIshF8638FDGEfTB8mgKFxWHeptsYhfQuL+jduHIO4A71Kv3uCDVl8CB6h3UpLkwFWqTBjVAI3B8p3S7btAp/dldwtSYIdo+liMT3798zN/XBQTtzD5ULXoD5bnNi3ThZkrVykI9plDLSwGo8w7i89M6XrM4KSWrItrcn+X/PEPybH+UwrKuuou3gCyjAHlXKweTdJijY4mAAced3dCoIUV2ZEkXo6o8inxem8EOmuUy615fNAg7VWRrplmhf1hOABSSeN625Y/mB18w8GGN92Wdt1annkH+pVOgZzcbhzLzXC/iRvJWb6vA5U0vaYcMS9aYTbjbElVUj2bmvbs2gSDG045/hv38dfjfTsLfc41BVaXALcR/dW6nTSuPDR3k+oXIWP2ofeMyQBIMfDeO4EqshGCHPYLFx+Qr+3Lak4RScLsHqKZ9wgI2UADiVMmQK8dTvZrhcsJixXury3gHxdStPG1K6sb8piDxfI0h8+hf2Wbrryz4QtiHXp/yhYIwaTI=
  on:
    tags: true
    repo: cdumay/kser-crypto
